ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/dispsys \
             -I$(MTK_PATH_PLATFORM)/drivers/videox \
             -I$(MTK_PATH_PLATFORM)/../../../kernel/drivers/video \
             -I$(MTK_PATH_PLATFORM)/../../common/kernel/drivers/cmdq \
             -I$(MTK_PATH_PLATFORM)/drivers/cmdq \
             

obj-y += smi_debug.o
obj-y += smi_common.o

